v1.0.5

diff --git a/.github/workflows/upload.yml b/.github/workflows/upload.yml
--- a/.github/workflows/upload.yml
+++ b/.github/workflows/upload.yml
@@ -30,14 +30,28 @@ jobs:
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
           restore-keys: |
             ${{ runner.os }}-gradle-
+      - name: Check if KEYSTORE_FILE is set
+        run: |
+          if [ -z "$KEYSTORE_FILE" ]; then
+            echo "KEYSTORE_FILE is not set!"
+            exit 1
+          else
+            echo "KEYSTORE_FILE is set."
+          fi
+
       - name: Decode keystore file
         run: |
           mkdir -p ~/.android
           echo "$KEYSTORE_FILE" | base64 --decode > ~/.android/debug.keystore
+          if [ ! -s ~/.android/debug.keystore ]; then
+            echo "Decoding failed, or the keystore file is empty."
+            exit 1
+          fi
+
       - name: Verify keystore file content
         run: |
           echo "Encoded keystore content:"
-          base64 ~/.android/debug.keystore
+          base64 ~/.android/debug.keystore || echo "Failed to read keystore content"
       - name: Build APK
         run: ./gradlew assembleDebug
         
